version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloud-clients'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6579:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  postgres-data:
  minio-data:
  redis-data:
