services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloud-clients'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    volumes:
      - .:/var/data
    ports:
      - '5432'
