version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloud-clients'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
